server:
  port: 8060

spring:
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${JDBC_CONNECTION_STRING}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    
#https://cryptotools.net/rsagen

app:
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6Q2lW4kepLJdZ4kauXed
      GNyjU9zS7K3BkvjVtDvuVUF46RiCoRSyCYIF7+0jKZVCxPCSslRnId9vavbsG2xp
      WEIURWkNiCAP0lKPm+hemQfjLIM1ZsUi8BU5Mzojp4vJW7MCC/OR9UKg1en5B1R8
      Wg0tP3/7ub5X0YtMZtUf1DrnGaGnbHMS1Ka5+AB+qfh9l9IpTr5qzHQJooUYPp2k
      qfO5B0Q17cAX05mktjQrK/JTKo7GkyK8NDc+oByL5aopzf4nZj+mk+L7O6LVHpKN
      d7OyFzQJG01nwNL1y6qWsndtgI02aRV1eRIQQBmg1n+ebvi/d25UniX37FT6rcR+
      BwIDAQAB
      -----END PUBLIC KEY-----
    private-key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA6Q2lW4kepLJdZ4kauXedGNyjU9zS7K3BkvjVtDvuVUF46RiC
      oRSyCYIF7+0jKZVCxPCSslRnId9vavbsG2xpWEIURWkNiCAP0lKPm+hemQfjLIM1
      ZsUi8BU5Mzojp4vJW7MCC/OR9UKg1en5B1R8Wg0tP3/7ub5X0YtMZtUf1DrnGaGn
      bHMS1Ka5+AB+qfh9l9IpTr5qzHQJooUYPp2kqfO5B0Q17cAX05mktjQrK/JTKo7G
      kyK8NDc+oByL5aopzf4nZj+mk+L7O6LVHpKNd7OyFzQJG01nwNL1y6qWsndtgI02
      aRV1eRIQQBmg1n+ebvi/d25UniX37FT6rcR+BwIDAQABAoIBAQDiCm9A+hzzp2B7
      BHscOozvyUjNFVirYNhowdsdBifjHy6z/ybsL5ODL06s6Dd7pJ7vP1s5hi3Fp958
      Q+S7sIn4pZbdv8f1KQvPdm59zIK8MO9BhD2uYTTC4gLp0dE1N5rkyxoIF4WQ+b/f
      2yDD4EkAWtlxRqQUAy9QOaiv8LT/dQxMGvxxlae8zWHs51RLiYl5nioDcjBLM4Tr
      AczphcefDlA5T+Ap1x/FkvN6O9wSaCGVLAIkW8oNas2vOcQhIPVkGagoMTTG19L9
      wbV7RV8y0iRspXByZqn+Yy8jkmVftZQw0rgFTu767AOxH5aFSt5uiqLEhSY6usVk
      SBPw8vgRAoGBAPZlnCSyz4HpNr+Hh975d181C3D8d5KYsVy9Bnr1T4G9DVL2iJEA
      o6yziQUFbWZJefa5Lh9XUWmZfDzvWUATSfoHfl+ysTxvLNy+7hdQ9ugjg1sJ1p8W
      c21MOQbUSeJkKdZNAr2DHZ5j8drX/VVxA39588uCyQcUqvn3HcJ5KlFfAoGBAPIi
      5uun9E9CcsY9SUkFW5dxrMoLHLs5QjGRb7akMjv0yCXg62tHj4W5JophhkDbtA8U
      cIMEnmcmt/MNBSeGAykGeEGDkZWUE/Qa0FkdaC6hGiwiInYIgwzHogjPmvPTPzOD
      oCb5LtMh2zq0xkRoz1Tj2bKdastRASvp/VEt2kxZAoGAaADl0rvDSTO2j0vW9zBX
      ydErHisDEdbv7pQ/OwF26O1yxVUYuhQKAmjZ6kurLOTQ3Wq25DXIQImv3kytYJWD
      wU0Oc7iKhVbsGdVhzGe5gK0U0gWqGQax/C2TWKWc9jmPS0zAXlwM0YGgYd6PqVQF
      xPYmCP4QerOno9FCN4dLbIMCgYB1i5n8lrlUbNaZBBF6oF45Y9bU8pYNEZvfwlGw
      IX+9eXRcZxcCKmgzK5HZJcTt4XpEw9Bm2iwnuTUdiZmR+U25ccmZTEy1h4A0RXwV
      duAnms/A0wVVtYYhAxzXGCmJ6mhJEsIBiYBAwLPTiQSjGxpjhIUfX6oDb5yY++uc
      qBzMaQKBgQCAwdbFZ16XPk838Mmygzk/A0ZrbS7SCiA1tPTOb1SemGRT+KuMP6Ov
      P9uRYuSqhkBnil20MXPbGF2nplpoYectyEaIB4KGQoUlmSTLkneDvsRWtXgYhatr
      SMCjxizbgEHMfC5MdcfswbLE5YtiSAX7NDfN+dNRb7Hv29bCBF6yww==
      -----END RSA PRIVATE KEY-----